### ISSUE TITLE
All the youtube videos have been removed

### ISSUE THREAD

**Issue by CloudZero458** [acgd-learn-the-web/www#25]
The youtube channel has been removed: [https://www.youtube.com/user/acinteractivedesign](https://www.youtube.com/user/acinteractivedesign)

**Comment by thomasjbradley** [comment]
Yes, thanks!
I’m fighting with Google to get the channel back online.

**Comment by CloudZero458** [comment]
Hello I was wondering if you have backups of all the videos?

**Comment by thomasjbradley** [comment]
Yes, I do have backups. But they are not in a convenient format. They are all Screenflow files, and I haven’t figured out a way to export them easily. There are ~500 individual files I’d have to export.

**Comment by CloudZero458** [comment]
Hi, are there any plans in the future to re-upload the videos?

**Comment by thomasjbradley** [comment]
@CloudZero458 I’ve re-encoded and uploaded all the video playlists!

You can see the playlists directly here:
https://videos.learntheweb.courses/

But they’re also linked at the top of all the written articles, e.g.
https://learntheweb.courses/topics/html-semantics/
